// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: client.proto

package coopstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchLevelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchLevelsRequest) Reset() {
	*x = FetchLevelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLevelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLevelsRequest) ProtoMessage() {}

func (x *FetchLevelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLevelsRequest.ProtoReflect.Descriptor instead.
func (*FetchLevelsRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type CreateLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player      *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Lobby       *LobbyId `protobuf:"bytes,2,opt,name=lobby,proto3" json:"lobby,omitempty"`
	Vacancy     *Vacancy `protobuf:"bytes,3,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	ChosenLevel *LevelId `protobuf:"bytes,4,opt,name=chosen_level,json=chosenLevel,proto3" json:"chosen_level,omitempty"`
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLobbyRequest) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *CreateLobbyRequest) GetLobby() *LobbyId {
	if x != nil {
		return x.Lobby
	}
	return nil
}

func (x *CreateLobbyRequest) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

func (x *CreateLobbyRequest) GetChosenLevel() *LevelId {
	if x != nil {
		return x.ChosenLevel
	}
	return nil
}

type FetchLobbiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchLobbiesRequest) Reset() {
	*x = FetchLobbiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLobbiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLobbiesRequest) ProtoMessage() {}

func (x *FetchLobbiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLobbiesRequest.ProtoReflect.Descriptor instead.
func (*FetchLobbiesRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Lobby  *LobbyId `protobuf:"bytes,2,opt,name=lobby,proto3" json:"lobby,omitempty"`
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *JoinLobbyRequest) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *JoinLobbyRequest) GetLobby() *LobbyId {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type LobbyFilledGameStartedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *LobbyFilledGameStartedResponse) Reset() {
	*x = LobbyFilledGameStartedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyFilledGameStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyFilledGameStartedResponse) ProtoMessage() {}

func (x *LobbyFilledGameStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyFilledGameStartedResponse.ProtoReflect.Descriptor instead.
func (*LobbyFilledGameStartedResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *LobbyFilledGameStartedResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type SendGameStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *SendGameStateResponse) Reset() {
	*x = SendGameStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGameStateResponse) ProtoMessage() {}

func (x *SendGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGameStateResponse.ProtoReflect.Descriptor instead.
func (*SendGameStateResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *SendGameStateResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type PutTowerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowerName string `protobuf:"bytes,1,opt,name=tower_name,json=towerName,proto3" json:"tower_name,omitempty"`
	Point     *Point `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *PutTowerRequest) Reset() {
	*x = PutTowerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutTowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTowerRequest) ProtoMessage() {}

func (x *PutTowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTowerRequest.ProtoReflect.Descriptor instead.
func (*PutTowerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *PutTowerRequest) GetTowerName() string {
	if x != nil {
		return x.TowerName
	}
	return ""
}

func (x *PutTowerRequest) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

type UpgradeTowerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower *TowerId `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
}

func (x *UpgradeTowerRequest) Reset() {
	*x = UpgradeTowerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeTowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeTowerRequest) ProtoMessage() {}

func (x *UpgradeTowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeTowerRequest.ProtoReflect.Descriptor instead.
func (*UpgradeTowerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradeTowerRequest) GetTower() *TowerId {
	if x != nil {
		return x.Tower
	}
	return nil
}

type TurnTowerOnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower *TowerId `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
}

func (x *TurnTowerOnRequest) Reset() {
	*x = TurnTowerOnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnTowerOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnTowerOnRequest) ProtoMessage() {}

func (x *TurnTowerOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnTowerOnRequest.ProtoReflect.Descriptor instead.
func (*TurnTowerOnRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *TurnTowerOnRequest) GetTower() *TowerId {
	if x != nil {
		return x.Tower
	}
	return nil
}

type ChangeTowerAimTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower      *TowerId `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
	NewAimType int32    `protobuf:"varint,2,opt,name=new_aim_type,json=newAimType,proto3" json:"new_aim_type,omitempty"`
}

func (x *ChangeTowerAimTypeRequest) Reset() {
	*x = ChangeTowerAimTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTowerAimTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTowerAimTypeRequest) ProtoMessage() {}

func (x *ChangeTowerAimTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTowerAimTypeRequest.ProtoReflect.Descriptor instead.
func (*ChangeTowerAimTypeRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeTowerAimTypeRequest) GetTower() *TowerId {
	if x != nil {
		return x.Tower
	}
	return nil
}

func (x *ChangeTowerAimTypeRequest) GetNewAimType() int32 {
	if x != nil {
		return x.NewAimType
	}
	return 0
}

type TurnTowerOffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower *TowerId `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
}

func (x *TurnTowerOffRequest) Reset() {
	*x = TurnTowerOffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnTowerOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnTowerOffRequest) ProtoMessage() {}

func (x *TurnTowerOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnTowerOffRequest.ProtoReflect.Descriptor instead.
func (*TurnTowerOffRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{10}
}

func (x *TurnTowerOffRequest) GetTower() *TowerId {
	if x != nil {
		return x.Tower
	}
	return nil
}

type SellTowerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower *TowerId `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
}

func (x *SellTowerRequest) Reset() {
	*x = SellTowerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellTowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellTowerRequest) ProtoMessage() {}

func (x *SellTowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellTowerRequest.ProtoReflect.Descriptor instead.
func (*SellTowerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{11}
}

func (x *SellTowerRequest) GetTower() *TowerId {
	if x != nil {
		return x.Tower
	}
	return nil
}

type StartNewWaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartNewWaveRequest) Reset() {
	*x = StartNewWaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNewWaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNewWaveRequest) ProtoMessage() {}

func (x *StartNewWaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNewWaveRequest.ProtoReflect.Descriptor instead.
func (*StartNewWaveRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{12}
}

type SlowGameDownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SlowGameDownRequest) Reset() {
	*x = SlowGameDownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowGameDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowGameDownRequest) ProtoMessage() {}

func (x *SlowGameDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowGameDownRequest.ProtoReflect.Descriptor instead.
func (*SlowGameDownRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{13}
}

type SpeedGameUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpeedGameUpRequest) Reset() {
	*x = SpeedGameUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpeedGameUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedGameUpRequest) ProtoMessage() {}

func (x *SpeedGameUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedGameUpRequest.ProtoReflect.Descriptor instead.
func (*SpeedGameUpRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{14}
}

type LeaveLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveLobbyRequest) Reset() {
	*x = LeaveLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyRequest) ProtoMessage() {}

func (x *LeaveLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyRequest.ProtoReflect.Descriptor instead.
func (*LeaveLobbyRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{15}
}

var File_client_proto protoreflect.FileDescriptor

var file_client_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x14, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xee, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74,
	0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x30, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x52, 0x05, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x12, 0x34, 0x0a, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f,
	0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x07,
	0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x3d, 0x0a, 0x0c, 0x63, 0x68, 0x6f, 0x73, 0x65,
	0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x52, 0x0b, 0x63, 0x68, 0x6f, 0x73, 0x65,
	0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c,
	0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x77, 0x0a,
	0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f,
	0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x52,
	0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x53, 0x0a, 0x1e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x46,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4a, 0x0a, 0x15, 0x53,
	0x65, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63,
	0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x60, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f,
	0x77, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x55, 0x70, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x30, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x52, 0x05, 0x74, 0x6f, 0x77,
	0x65, 0x72, 0x22, 0x46, 0x0a, 0x12, 0x54, 0x75, 0x72, 0x6e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x4f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x6f, 0x77, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x19, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x41, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x65, 0x77,
	0x5f, 0x61, 0x69, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6e, 0x65, 0x77, 0x41, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x54,
	0x75, 0x72, 0x6e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x52, 0x05, 0x74,
	0x6f, 0x77, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x6c, 0x54, 0x6f, 0x77, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x6f, 0x77, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x6c, 0x6f, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13,
	0x0a, 0x11, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2d, 0x63, 0x6f, 0x2f, 0x74, 0x64, 0x2d, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6f, 0x70, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData = file_client_proto_rawDesc
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_proto_rawDescData)
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_client_proto_goTypes = []interface{}{
	(*FetchLevelsRequest)(nil),             // 0: td_game.coopstate.FetchLevelsRequest
	(*CreateLobbyRequest)(nil),             // 1: td_game.coopstate.CreateLobbyRequest
	(*FetchLobbiesRequest)(nil),            // 2: td_game.coopstate.FetchLobbiesRequest
	(*JoinLobbyRequest)(nil),               // 3: td_game.coopstate.JoinLobbyRequest
	(*LobbyFilledGameStartedResponse)(nil), // 4: td_game.coopstate.LobbyFilledGameStartedResponse
	(*SendGameStateResponse)(nil),          // 5: td_game.coopstate.SendGameStateResponse
	(*PutTowerRequest)(nil),                // 6: td_game.coopstate.PutTowerRequest
	(*UpgradeTowerRequest)(nil),            // 7: td_game.coopstate.UpgradeTowerRequest
	(*TurnTowerOnRequest)(nil),             // 8: td_game.coopstate.TurnTowerOnRequest
	(*ChangeTowerAimTypeRequest)(nil),      // 9: td_game.coopstate.ChangeTowerAimTypeRequest
	(*TurnTowerOffRequest)(nil),            // 10: td_game.coopstate.TurnTowerOffRequest
	(*SellTowerRequest)(nil),               // 11: td_game.coopstate.SellTowerRequest
	(*StartNewWaveRequest)(nil),            // 12: td_game.coopstate.StartNewWaveRequest
	(*SlowGameDownRequest)(nil),            // 13: td_game.coopstate.SlowGameDownRequest
	(*SpeedGameUpRequest)(nil),             // 14: td_game.coopstate.SpeedGameUpRequest
	(*LeaveLobbyRequest)(nil),              // 15: td_game.coopstate.LeaveLobbyRequest
	(*Player)(nil),                         // 16: td_game.coopstate.Player
	(*LobbyId)(nil),                        // 17: td_game.coopstate.LobbyId
	(*Vacancy)(nil),                        // 18: td_game.coopstate.Vacancy
	(*LevelId)(nil),                        // 19: td_game.coopstate.LevelId
	(Status)(0),                            // 20: td_game.coopstate.Status
	(*Point)(nil),                          // 21: td_game.coopstate.Point
	(*TowerId)(nil),                        // 22: td_game.coopstate.TowerId
}
var file_client_proto_depIdxs = []int32{
	16, // 0: td_game.coopstate.CreateLobbyRequest.player:type_name -> td_game.coopstate.Player
	17, // 1: td_game.coopstate.CreateLobbyRequest.lobby:type_name -> td_game.coopstate.LobbyId
	18, // 2: td_game.coopstate.CreateLobbyRequest.vacancy:type_name -> td_game.coopstate.Vacancy
	19, // 3: td_game.coopstate.CreateLobbyRequest.chosen_level:type_name -> td_game.coopstate.LevelId
	16, // 4: td_game.coopstate.JoinLobbyRequest.player:type_name -> td_game.coopstate.Player
	17, // 5: td_game.coopstate.JoinLobbyRequest.lobby:type_name -> td_game.coopstate.LobbyId
	20, // 6: td_game.coopstate.LobbyFilledGameStartedResponse.status:type_name -> td_game.coopstate.Status
	20, // 7: td_game.coopstate.SendGameStateResponse.status:type_name -> td_game.coopstate.Status
	21, // 8: td_game.coopstate.PutTowerRequest.point:type_name -> td_game.coopstate.Point
	22, // 9: td_game.coopstate.UpgradeTowerRequest.tower:type_name -> td_game.coopstate.TowerId
	22, // 10: td_game.coopstate.TurnTowerOnRequest.tower:type_name -> td_game.coopstate.TowerId
	22, // 11: td_game.coopstate.ChangeTowerAimTypeRequest.tower:type_name -> td_game.coopstate.TowerId
	22, // 12: td_game.coopstate.TurnTowerOffRequest.tower:type_name -> td_game.coopstate.TowerId
	22, // 13: td_game.coopstate.SellTowerRequest.tower:type_name -> td_game.coopstate.TowerId
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLevelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLobbiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LobbyFilledGameStartedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGameStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutTowerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeTowerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TurnTowerOnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTowerAimTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TurnTowerOffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellTowerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNewWaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowGameDownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpeedGameUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_rawDesc = nil
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
