// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: server.proto

package coopstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchLevelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Levels []*LevelId `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty"`
}

func (x *FetchLevelsResponse) Reset() {
	*x = FetchLevelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLevelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLevelsResponse) ProtoMessage() {}

func (x *FetchLevelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLevelsResponse.ProtoReflect.Descriptor instead.
func (*FetchLevelsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *FetchLevelsResponse) GetLevels() []*LevelId {
	if x != nil {
		return x.Levels
	}
	return nil
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobby  *Lobby `protobuf:"bytes,1,opt,name=lobby,proto3,oneof" json:"lobby,omitempty"`
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

func (x *CreateLobbyResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type FetchLobbiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobbies []*Lobby `protobuf:"bytes,1,rep,name=lobbies,proto3" json:"lobbies,omitempty"`
}

func (x *FetchLobbiesResponse) Reset() {
	*x = FetchLobbiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLobbiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLobbiesResponse) ProtoMessage() {}

func (x *FetchLobbiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLobbiesResponse.ProtoReflect.Descriptor instead.
func (*FetchLobbiesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *FetchLobbiesResponse) GetLobbies() []*Lobby {
	if x != nil {
		return x.Lobbies
	}
	return nil
}

type JoinLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
	// Types that are assignable to Response:
	//
	//	*JoinLobbyResponse_PutTower
	//	*JoinLobbyResponse_StartNewWave
	//	*JoinLobbyResponse_SpeedUp
	//	*JoinLobbyResponse_SlowDown
	//	*JoinLobbyResponse_UpgradeTower
	//	*JoinLobbyResponse_SellTower
	//	*JoinLobbyResponse_TurnOn
	//	*JoinLobbyResponse_TurnOff
	//	*JoinLobbyResponse_TuneTower
	Response isJoinLobbyResponse_Response `protobuf_oneof:"response"`
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *JoinLobbyResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (m *JoinLobbyResponse) GetResponse() isJoinLobbyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *JoinLobbyResponse) GetPutTower() *PutTowerRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_PutTower); ok {
		return x.PutTower
	}
	return nil
}

func (x *JoinLobbyResponse) GetStartNewWave() *StartNewWaveRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_StartNewWave); ok {
		return x.StartNewWave
	}
	return nil
}

func (x *JoinLobbyResponse) GetSpeedUp() *SpeedGameUpRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_SpeedUp); ok {
		return x.SpeedUp
	}
	return nil
}

func (x *JoinLobbyResponse) GetSlowDown() *SlowGameDownRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_SlowDown); ok {
		return x.SlowDown
	}
	return nil
}

func (x *JoinLobbyResponse) GetUpgradeTower() *UpgradeTowerRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_UpgradeTower); ok {
		return x.UpgradeTower
	}
	return nil
}

func (x *JoinLobbyResponse) GetSellTower() *SellTowerRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_SellTower); ok {
		return x.SellTower
	}
	return nil
}

func (x *JoinLobbyResponse) GetTurnOn() *TurnTowerOnRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_TurnOn); ok {
		return x.TurnOn
	}
	return nil
}

func (x *JoinLobbyResponse) GetTurnOff() *TurnTowerOffRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_TurnOff); ok {
		return x.TurnOff
	}
	return nil
}

func (x *JoinLobbyResponse) GetTuneTower() *TuneTowerRequest {
	if x, ok := x.GetResponse().(*JoinLobbyResponse_TuneTower); ok {
		return x.TuneTower
	}
	return nil
}

type isJoinLobbyResponse_Response interface {
	isJoinLobbyResponse_Response()
}

type JoinLobbyResponse_PutTower struct {
	PutTower *PutTowerRequest `protobuf:"bytes,2,opt,name=putTower,proto3,oneof"`
}

type JoinLobbyResponse_StartNewWave struct {
	StartNewWave *StartNewWaveRequest `protobuf:"bytes,3,opt,name=startNewWave,proto3,oneof"`
}

type JoinLobbyResponse_SpeedUp struct {
	SpeedUp *SpeedGameUpRequest `protobuf:"bytes,4,opt,name=speedUp,proto3,oneof"`
}

type JoinLobbyResponse_SlowDown struct {
	SlowDown *SlowGameDownRequest `protobuf:"bytes,5,opt,name=slowDown,proto3,oneof"`
}

type JoinLobbyResponse_UpgradeTower struct {
	UpgradeTower *UpgradeTowerRequest `protobuf:"bytes,6,opt,name=upgradeTower,proto3,oneof"`
}

type JoinLobbyResponse_SellTower struct {
	SellTower *SellTowerRequest `protobuf:"bytes,7,opt,name=sellTower,proto3,oneof"`
}

type JoinLobbyResponse_TurnOn struct {
	TurnOn *TurnTowerOnRequest `protobuf:"bytes,8,opt,name=turnOn,proto3,oneof"`
}

type JoinLobbyResponse_TurnOff struct {
	TurnOff *TurnTowerOffRequest `protobuf:"bytes,9,opt,name=turnOff,proto3,oneof"`
}

type JoinLobbyResponse_TuneTower struct {
	TuneTower *TuneTowerRequest `protobuf:"bytes,10,opt,name=tuneTower,proto3,oneof"`
}

func (*JoinLobbyResponse_PutTower) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_StartNewWave) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_SpeedUp) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_SlowDown) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_UpgradeTower) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_SellTower) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_TurnOn) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_TurnOff) isJoinLobbyResponse_Response() {}

func (*JoinLobbyResponse_TuneTower) isJoinLobbyResponse_Response() {}

type AwaitGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level     string   `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Nicknames []string `protobuf:"bytes,2,rep,name=nicknames,proto3" json:"nicknames,omitempty"`
}

func (x *AwaitGameResponse) Reset() {
	*x = AwaitGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwaitGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitGameResponse) ProtoMessage() {}

func (x *AwaitGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitGameResponse.ProtoReflect.Descriptor instead.
func (*AwaitGameResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *AwaitGameResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AwaitGameResponse) GetNicknames() []string {
	if x != nil {
		return x.Nicknames
	}
	return nil
}

type SendGameStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendGameStateRequest) Reset() {
	*x = SendGameStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGameStateRequest) ProtoMessage() {}

func (x *SendGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGameStateRequest.ProtoReflect.Descriptor instead.
func (*SendGameStateRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

type PutTowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"` //  optional PlayerState new_state = 2;
}

func (x *PutTowerResponse) Reset() {
	*x = PutTowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTowerResponse) ProtoMessage() {}

func (x *PutTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTowerResponse.ProtoReflect.Descriptor instead.
func (*PutTowerResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *PutTowerResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type UpgradeTowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *UpgradeTowerResponse) Reset() {
	*x = UpgradeTowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeTowerResponse) ProtoMessage() {}

func (x *UpgradeTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeTowerResponse.ProtoReflect.Descriptor instead.
func (*UpgradeTowerResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradeTowerResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type TurnTowerOnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *TurnTowerOnResponse) Reset() {
	*x = TurnTowerOnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnTowerOnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnTowerOnResponse) ProtoMessage() {}

func (x *TurnTowerOnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnTowerOnResponse.ProtoReflect.Descriptor instead.
func (*TurnTowerOnResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *TurnTowerOnResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type TurnTowerOffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *TurnTowerOffResponse) Reset() {
	*x = TurnTowerOffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnTowerOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnTowerOffResponse) ProtoMessage() {}

func (x *TurnTowerOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnTowerOffResponse.ProtoReflect.Descriptor instead.
func (*TurnTowerOffResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *TurnTowerOffResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type ChangeTowerAimTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *ChangeTowerAimTypeResponse) Reset() {
	*x = ChangeTowerAimTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTowerAimTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTowerAimTypeResponse) ProtoMessage() {}

func (x *ChangeTowerAimTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTowerAimTypeResponse.ProtoReflect.Descriptor instead.
func (*ChangeTowerAimTypeResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeTowerAimTypeResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type SellTowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// optional PlayerState player = 1;
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *SellTowerResponse) Reset() {
	*x = SellTowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellTowerResponse) ProtoMessage() {}

func (x *SellTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellTowerResponse.ProtoReflect.Descriptor instead.
func (*SellTowerResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *SellTowerResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type StartNewWaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *StartNewWaveResponse) Reset() {
	*x = StartNewWaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNewWaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNewWaveResponse) ProtoMessage() {}

func (x *StartNewWaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNewWaveResponse.ProtoReflect.Descriptor instead.
func (*StartNewWaveResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *StartNewWaveResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type SlowGameDownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *SlowGameDownResponse) Reset() {
	*x = SlowGameDownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowGameDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowGameDownResponse) ProtoMessage() {}

func (x *SlowGameDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowGameDownResponse.ProtoReflect.Descriptor instead.
func (*SlowGameDownResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *SlowGameDownResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type SpeedGameUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *SpeedGameUpResponse) Reset() {
	*x = SpeedGameUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpeedGameUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedGameUpResponse) ProtoMessage() {}

func (x *SpeedGameUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedGameUpResponse.ProtoReflect.Descriptor instead.
func (*SpeedGameUpResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *SpeedGameUpResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type LeaveLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *LeaveLobbyResponse) Reset() {
	*x = LeaveLobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyResponse) ProtoMessage() {}

func (x *LeaveLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyResponse.ProtoReflect.Descriptor instead.
func (*LeaveLobbyResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *LeaveLobbyResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type TuneTowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=td_game.coopstate.Status" json:"status,omitempty"`
}

func (x *TuneTowerResponse) Reset() {
	*x = TuneTowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuneTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneTowerResponse) ProtoMessage() {}

func (x *TuneTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneTowerResponse.ProtoReflect.Descriptor instead.
func (*TuneTowerResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{16}
}

func (x *TuneTowerResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

var File_server_proto protoreflect.FileDescriptor

var file_server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a,
	0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63,
	0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64,
	0x52, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x22, 0x4a, 0x0a, 0x14, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x62, 0x62, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x6c, 0x6f,
	0x62, 0x62, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x64,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x22, 0xc8,
	0x05, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63,
	0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x75, 0x74, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x64, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x75,
	0x74, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4e, 0x65, 0x77, 0x57, 0x61, 0x76, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x55, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x70, 0x65,
	0x65, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x07, 0x73, 0x70, 0x65, 0x65, 0x64, 0x55, 0x70, 0x12, 0x44, 0x0a, 0x08, 0x73, 0x6c,
	0x6f, 0x77, 0x44, 0x6f, 0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74,
	0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x53, 0x6c, 0x6f, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x77, 0x6e,
	0x12, 0x4c, 0x0a, 0x0c, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0c, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x43,
	0x0a, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f,
	0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x75, 0x72, 0x6e, 0x54, 0x6f, 0x77, 0x65,
	0x72, 0x4f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x74, 0x75,
	0x72, 0x6e, 0x4f, 0x6e, 0x12, 0x42, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x66, 0x66, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x75, 0x72, 0x6e, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x66, 0x66, 0x12, 0x43, 0x0a, 0x09, 0x74, 0x75, 0x6e, 0x65,
	0x54, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x64,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x54, 0x75, 0x6e, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x74, 0x75, 0x6e, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x0a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x11, 0x41, 0x77, 0x61,
	0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x10, 0x50, 0x75,
	0x74, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x49, 0x0a, 0x14, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x54, 0x6f, 0x77, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x48, 0x0a, 0x13,
	0x54, 0x75, 0x72, 0x6e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f,
	0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x14, 0x54, 0x75, 0x72, 0x6e, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x4f, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72,
	0x41, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x53, 0x65, 0x6c, 0x6c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x14, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f,
	0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x14, 0x53, 0x6c, 0x6f, 0x77, 0x47, 0x61, 0x6d,
	0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x48, 0x0a, 0x13, 0x53, 0x70, 0x65, 0x65, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x12, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x54, 0x75, 0x6e, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x64, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72,
	0x2d, 0x63, 0x6f, 0x2f, 0x74, 0x64, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData = file_server_proto_rawDesc
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_rawDescData)
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_server_proto_goTypes = []any{
	(*FetchLevelsResponse)(nil),        // 0: td_game.coopstate.FetchLevelsResponse
	(*CreateLobbyResponse)(nil),        // 1: td_game.coopstate.CreateLobbyResponse
	(*FetchLobbiesResponse)(nil),       // 2: td_game.coopstate.FetchLobbiesResponse
	(*JoinLobbyResponse)(nil),          // 3: td_game.coopstate.JoinLobbyResponse
	(*AwaitGameResponse)(nil),          // 4: td_game.coopstate.AwaitGameResponse
	(*SendGameStateRequest)(nil),       // 5: td_game.coopstate.SendGameStateRequest
	(*PutTowerResponse)(nil),           // 6: td_game.coopstate.PutTowerResponse
	(*UpgradeTowerResponse)(nil),       // 7: td_game.coopstate.UpgradeTowerResponse
	(*TurnTowerOnResponse)(nil),        // 8: td_game.coopstate.TurnTowerOnResponse
	(*TurnTowerOffResponse)(nil),       // 9: td_game.coopstate.TurnTowerOffResponse
	(*ChangeTowerAimTypeResponse)(nil), // 10: td_game.coopstate.ChangeTowerAimTypeResponse
	(*SellTowerResponse)(nil),          // 11: td_game.coopstate.SellTowerResponse
	(*StartNewWaveResponse)(nil),       // 12: td_game.coopstate.StartNewWaveResponse
	(*SlowGameDownResponse)(nil),       // 13: td_game.coopstate.SlowGameDownResponse
	(*SpeedGameUpResponse)(nil),        // 14: td_game.coopstate.SpeedGameUpResponse
	(*LeaveLobbyResponse)(nil),         // 15: td_game.coopstate.LeaveLobbyResponse
	(*TuneTowerResponse)(nil),          // 16: td_game.coopstate.TuneTowerResponse
	(*LevelId)(nil),                    // 17: td_game.coopstate.LevelId
	(*Lobby)(nil),                      // 18: td_game.coopstate.Lobby
	(Status)(0),                        // 19: td_game.coopstate.Status
	(*PutTowerRequest)(nil),            // 20: td_game.coopstate.PutTowerRequest
	(*StartNewWaveRequest)(nil),        // 21: td_game.coopstate.StartNewWaveRequest
	(*SpeedGameUpRequest)(nil),         // 22: td_game.coopstate.SpeedGameUpRequest
	(*SlowGameDownRequest)(nil),        // 23: td_game.coopstate.SlowGameDownRequest
	(*UpgradeTowerRequest)(nil),        // 24: td_game.coopstate.UpgradeTowerRequest
	(*SellTowerRequest)(nil),           // 25: td_game.coopstate.SellTowerRequest
	(*TurnTowerOnRequest)(nil),         // 26: td_game.coopstate.TurnTowerOnRequest
	(*TurnTowerOffRequest)(nil),        // 27: td_game.coopstate.TurnTowerOffRequest
	(*TuneTowerRequest)(nil),           // 28: td_game.coopstate.TuneTowerRequest
}
var file_server_proto_depIdxs = []int32{
	17, // 0: td_game.coopstate.FetchLevelsResponse.levels:type_name -> td_game.coopstate.LevelId
	18, // 1: td_game.coopstate.CreateLobbyResponse.lobby:type_name -> td_game.coopstate.Lobby
	19, // 2: td_game.coopstate.CreateLobbyResponse.status:type_name -> td_game.coopstate.Status
	18, // 3: td_game.coopstate.FetchLobbiesResponse.lobbies:type_name -> td_game.coopstate.Lobby
	19, // 4: td_game.coopstate.JoinLobbyResponse.status:type_name -> td_game.coopstate.Status
	20, // 5: td_game.coopstate.JoinLobbyResponse.putTower:type_name -> td_game.coopstate.PutTowerRequest
	21, // 6: td_game.coopstate.JoinLobbyResponse.startNewWave:type_name -> td_game.coopstate.StartNewWaveRequest
	22, // 7: td_game.coopstate.JoinLobbyResponse.speedUp:type_name -> td_game.coopstate.SpeedGameUpRequest
	23, // 8: td_game.coopstate.JoinLobbyResponse.slowDown:type_name -> td_game.coopstate.SlowGameDownRequest
	24, // 9: td_game.coopstate.JoinLobbyResponse.upgradeTower:type_name -> td_game.coopstate.UpgradeTowerRequest
	25, // 10: td_game.coopstate.JoinLobbyResponse.sellTower:type_name -> td_game.coopstate.SellTowerRequest
	26, // 11: td_game.coopstate.JoinLobbyResponse.turnOn:type_name -> td_game.coopstate.TurnTowerOnRequest
	27, // 12: td_game.coopstate.JoinLobbyResponse.turnOff:type_name -> td_game.coopstate.TurnTowerOffRequest
	28, // 13: td_game.coopstate.JoinLobbyResponse.tuneTower:type_name -> td_game.coopstate.TuneTowerRequest
	19, // 14: td_game.coopstate.PutTowerResponse.status:type_name -> td_game.coopstate.Status
	19, // 15: td_game.coopstate.UpgradeTowerResponse.status:type_name -> td_game.coopstate.Status
	19, // 16: td_game.coopstate.TurnTowerOnResponse.status:type_name -> td_game.coopstate.Status
	19, // 17: td_game.coopstate.TurnTowerOffResponse.status:type_name -> td_game.coopstate.Status
	19, // 18: td_game.coopstate.ChangeTowerAimTypeResponse.status:type_name -> td_game.coopstate.Status
	19, // 19: td_game.coopstate.SellTowerResponse.status:type_name -> td_game.coopstate.Status
	19, // 20: td_game.coopstate.StartNewWaveResponse.status:type_name -> td_game.coopstate.Status
	19, // 21: td_game.coopstate.SlowGameDownResponse.status:type_name -> td_game.coopstate.Status
	19, // 22: td_game.coopstate.SpeedGameUpResponse.status:type_name -> td_game.coopstate.Status
	19, // 23: td_game.coopstate.LeaveLobbyResponse.status:type_name -> td_game.coopstate.Status
	19, // 24: td_game.coopstate.TuneTowerResponse.status:type_name -> td_game.coopstate.Status
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_common_proto_init()
	file_client_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FetchLevelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FetchLobbiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*JoinLobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AwaitGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SendGameStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PutTowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpgradeTowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TurnTowerOnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*TurnTowerOffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeTowerAimTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SellTowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*StartNewWaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SlowGameDownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SpeedGameUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*LeaveLobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*TuneTowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_server_proto_msgTypes[1].OneofWrappers = []any{}
	file_server_proto_msgTypes[3].OneofWrappers = []any{
		(*JoinLobbyResponse_PutTower)(nil),
		(*JoinLobbyResponse_StartNewWave)(nil),
		(*JoinLobbyResponse_SpeedUp)(nil),
		(*JoinLobbyResponse_SlowDown)(nil),
		(*JoinLobbyResponse_UpgradeTower)(nil),
		(*JoinLobbyResponse_SellTower)(nil),
		(*JoinLobbyResponse_TurnOn)(nil),
		(*JoinLobbyResponse_TurnOff)(nil),
		(*JoinLobbyResponse_TuneTower)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_rawDesc = nil
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
