package models

import "image"

// Projectile is an entity generated by towers that flies to the enemy
// and deals the damage to it.
// Projectiles never misses the enemy and achieves the aim when TTL is equal to zero.
type Projectile struct {
	Pos         Point // current position on a map
	Vrms        Coord
	Vx          Coord
	Vy          Coord
	Type        TypeAttack
	Damage      int
	TTL         Frames
	TargetEnemy *Enemy
	Image       image.Image
}

// Move moves the projectile on the map.
func (p *Projectile) Move() {
	p.Pos.X += p.Vx
	p.Pos.Y += p.Vy
	p.TTL--
}

// EnemyHit checks if the projectile hit the enemy and returns true if it is.
func (p *Projectile) EnemyHit() bool {
	if p.TTL == 0 {
		p.TargetEnemy.DealDamage(p.TargetEnemy.FinalDamage(p.Type, p.Damage))
		return true
	}
	return false
}
